### ISSUE TITLE
Developer_Story 6.1: Aufbau einer Server-API zur Chat-Kommunikation: Installation auf lokalem Rechner 

### ISSUE THREAD

**Issue by ghost** [pA1nD/ng-chatapp#17]
Tasks:
- [x] Implementierung auf lokalem Rechner oder auf Cloudserver
- [x] Erstellen der Funktion: "History schreiben und lesen"

AK:
- [x] Implementierung auf dem lokalen Rechner oder auf Cloudserver
- [x] History kann geschrieben und gelesen werden
- [x] Verbindung muss nicht https/ssl verschlüsselt sein (optional)

**Comment by AlexanderZuendorf** [comment]
Timestamp ist bei allen Nachrichten derselbe
