### ISSUE TITLE
Dev: Story 7 - Überarbeitung der App (20% der Gesamtnote)

### ISSUE THREAD

**Issue by ghost** [pA1nD/ng-chatapp#22]
Story 7: Design (und Funktionen) der App überarbeiten

- [x] Grundfunktionen müssen erhalten bleiben (Nickname, Timestamp, Timing, etc.)
- [ ] App auf Server laden
- [x] Nachricht muss spätestens nach 5s dargestellt werden
- [x] kein Scrollen, d.h. neue Nachricht ist im Textfeld direkt ersichtlich
- [x] Inizialen wird Nickname zugeordnet und ist in History ersichtlich
- [x] weitere coole Funktionen ... 😃 
- [x] Messages kommen nicht instant sondern man muss refreshen
- [x] Timestamp funktioniert nicht
- [x] Header mit Logo und Namen: "lemon-chat"
- [x] in Footer Copyright und Jahreszahl
- [ ] Impressum
- [x] ev. Anzeige, wie viel Chatbenutzer online sind
- [x] eigene Message andere Farbe und auf der rechten Seite
- [ ] Accounts für Avatare erstellen
- [x] Skript, jemand geht raus, OS im Namen erwähnen
- [x] wenn das Eingabefeld leer ist sollte man das nicht abschicken können, was aber jetzt noch der Fall ist

Design
- [x] e-Lemon-ators Logo anstelle HSG-Logo 
- [x] Farbe des Designs auf Logo abstimmen
- [x] Hintergrund des Chats ändern (Bildquelle Björn)
- [x] Bild des Users einfügen in Chat
- [x] responsive Design für Präsentation der App auf Tablet, PC/Mac, Smartphone

**Comment by pA1nD** [comment]
Avatar via Gravatar (https://github.com/wallin/angular-gravatar)

**Comment by pA1nD** [comment]
Sentiment:

https://www.npmjs.com/package/sentiment
https://github.com/syzer/sentiment-analyser
