### ISSUE TITLE
Story 4: Fortlaufendes History Feld

### ISSUE THREAD

**Issue by AlexanderZuendorf** [pA1nD/ng-chatapp#7]
Versendete Nachrichten sollen in fortlaufender Anzeige in einem History Feld ausgegeben werden.

Akzeptanzkriterien:
- Neuer Text erscheint in neuer Zeile
- Neuer Text erscheint unter altem Text

Tasks
- Kick-Off
- History Feld erstellen
- Styling
- Testing

**Comment by AlexanderZuendorf** [comment]
5 Story Points

**Comment by Ivan-C137** [comment]
9
