### ISSUE TITLE
Story 5: Nicknamen

### ISSUE THREAD

**Issue by AlexanderZuendorf** [pA1nD/ng-chatapp#8]
Der Nickname des Anwenders wird vor der Nachricht dargestellt

Akzeptanzkriterien
- Nickname muss erstellt werden können
- Nickname wird vor jeder neuen Nachricht dargestellt
- Nickname wird bei Mehrzeiligen Nachrichten nur in der ersten Zeile dargestellt

Tasks
- Kick off
- Nicknamenerstellungsfeld erstellen
- Nicknamen bei den Nachrichten im History Feld einbinden
- Styling 
- Testing

**Comment by AlexanderZuendorf** [comment]
8 Story Points

**Comment by Ivan-C137** [comment]
12 points
